FROM codebase_backend_kit:latest as codebase

    COPY ./codebase/backend .
    RUN if [ -e package.json ]; then npm install --legacy-peer-deps; fi;
    RUN if [ -e composer.json ]; then composer install; fi;